### ISSUE TITLE
Ember.HTMLBars.compile is not a function

### ISSUE THREAD

**Issue by nlalonde** [sitepoint/discourse-theme#97]
We noticed in the javascript console that there is an error because of this line:

https://github.com/sitepoint/discourse-theme/blob/master/assets/javascripts/discourse/components/maestro-sub.js.es6#L4

Maybe it needs to be changed to `Ember.HTMLBars.template`?

**Comment by mrlagmer** [comment]
Closed by: https://github.com/sitepoint/discourse-theme/pull/98

**Comment by nlalonde** [comment]
That's the same code we already have deployed.

https://github.com/discourse-org/discourse-sitepoint/blob/master/assets/javascripts/discourse/components/maestro-sub.js.es6

Can you ship the templates in the plugin instead of compiling them in maestro-sub?
